### ISSUE TITLE
Searches all return errors

### ISSUE THREAD

**Issue by morganestes** [ravikiranj/hubot-imdb#1]
Looks like the URL used to query IMDB doesn't work anymore. It returns a 404, which breaks the JSON parser in the script.

**Comment by ravikiranj** [comment]
Thank you for reporting the issue. I have fixed it and migrated the bot to use  http://www.omdbapi.com/apikey.aspx. Please checkout the latest [README.md](https://github.com/ravikiranj/hubot-imdb/blob/master/README.md) for instructions.

I have also pushed a new version to https://www.npmjs.com/package/hubot-imdb
